@startuml
' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "Usuário" as e01 {
  *id_usuário: number <<generated>>
  --
  name : text
  idade: number
  cpf: number 
  email: number
  admin: boolean
  avaliação : number
}

entity "Pet" as e02 {
  *id_pet : number <<generated>>
  --
  *id_usuario: number <<FK>>
  name : text
  idade : number
  peso : number
  raça : text
  descrição : text
  fotos : longblob

}

entity "Avaliações" as e03 {
  *id_aval : number <<generated>>
  --
  *id_usuario: number <<FK>>
  qtdEstrela : number
  descrição : text
}


entity "AvaliaçãoMapa" as e04 {
  *id_avalMapa : number <<generated>>
  --
  *id_usuario : number 
  coords: text
  qtdEstrela : number<<FK>>
  descrição : text
}

entity "Publicações" as e05 {
  *id_pub : number <<generated>>
  --
  *id_usuario : number <<FK>>
  *id_pet : number <<FK>>
   titulo : text
   descrição : text
   fotos : longblob
}


entity "Conversa" as e06 {
  *id_chat : number <<generated>>
  --
  *id_usuario1 : number <<FK>>
  *id_usuario2 : number <<FK>>  
}

entity "Mensagem" as e07 {
  *id_mensagem : number <<generated>>
  --
  *id_chat : number <<FK>>
  conteudo : text
}

entity "Report" as e08 {
 *id_report : number <<generated>>
  --
  *id_usuario: number <<FK>>
  tipo : number
  comentario : text
}

e01 ||..o{ e02
e01 ||..o{ e03
e01 }o..|{ e06
e01 }o..|| e05
e05 ||..o| e02
e08 ||..o{ e01
e04 ||..o{ e01
e07 ||..o{ e06
@enduml
