
@startuml GetPet
skinparam actorStyle awesome
:Admin: as admin
:Usuário: as user

(controlarFavoritos)
(enviarReport)
(controlarReport)
(controlarChat)
(controlarAdoção)
(controlarUsuario)
(sucEfetuarLogin)

user <|-- admin
user --> controlarFavoritos
user --> enviarReport
user --> controlarReport
user --> controlarChat
user --> controlarAdoção
user --> controlarUsuario
user --> sucEfetuarLogin

@enduml


